# .github/workflows/firebase-hosting-merge.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master   # если у тебя основная ветка master, оставь так
      # - main    # если у тебя main, поменяй тут

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Установим Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Установим зависимости
      - run: npm install

      # Соберем проект
      - run: npm run build

      # Деплой на Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEAK_PROTECTION }}
          channelId: live
          projectId: leak-protection
